### PR TITLE
Updated all android studio and gradle files to latest, and deleted unused resources.

### PR DESCRIPTION
**Pull request by heypaulmcgrath**
Deleted unnecessary nav drawer drawables, as the current version of the app uses the new material ActionBarDrawerToggle.

Updated maven repo to jcenter, which is the new default.
Updated compile task type.
Updated build and tool versions.
Updated all gradle tasks to current naming schemes.
Updated gradle-wrapper.

Removed signing config as the following process is standard now:
Go to Build -> Generate Signed APK. Create your key (or choose existing) -> next -> next -> done!

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Dang didn't see this pull request before I created one of my own. Is this project being maintained? Does seem like pull requests are getting accepted...

**Comment by heypaulmcgrath** [comment]
Yeah, I think the dev has just given it a break for a while. Might accept the pull requests when they're ready.

**Comment by msdx** [comment]
+1

**Comment by Jawnnypoo** [comment]
This has been done in my pull

https://github.com/Commit451/GitLabAndroid

**Comment by msdx** [comment]
In my fork, I used the better solution to package `.so` files:
https://github.com/msdx/GitLabAndroid/commit/d99336fc44a5e1e542b5b77e9305f6d2c2d94b27
Just copy the `.so` files to the conventional directory `app/src/main/jniLibs`

**Comment by Jawnnypoo** [comment]
Yeah, so I did try that. Looks like it wants me to install the NDK when I do that, which shouldn't be required to build the project. Do you not have that issue too?

**Comment by heypaulmcgrath** [comment]
There seems to be no interest in this project, so i'm closing the pull request as it's already been done by a couple of others.

**Comment by msdx** [comment]
In my fork, it didn't need to install the NDK when I do that.

**Pull request closed without merging**
